### ISSUE TITLE
how to test --consensus_type MLP --arch squeezenet1_1 after training dataset?

### ISSUE THREAD

**Issue by ranjitswami** [fubel/stmodeling#3]
Hello,

I have trained jester dataset with MLP --arch squeezenet1_1, I have used test_video.py from TRN-pytorch but getting followig error.

 Initializing TSN with base model: BNInception.
    TSN Configurations:
        input_modality:     RGB
        num_segments:       8
        new_length:         1
        consensus_module:   MLP
        dropout_ratio:      0.5
        img_feature_dim:    256
            
Traceback (most recent call last):
  File "test_video.py", line 122, in <module>
    net.load_state_dict(base_dict)
  File "/home/test/anaconda3/lib/python2.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TSN:
	Missing key(s) in state_dict: "base_model.conv1_7x7_s2.bias", "base_model.conv1_7x7_s2.weight", "base_model.conv1_7x7_s2_bn.running_var", "base_model.conv1_7x7_s2_bn.bias", "base_model.conv1_7x7_s2_bn.weight", "base_model.conv1_7x7_s2_bn.running_mean", "base_model.conv2_3x3_reduce.bias", "base_model.conv2_3x3_reduce.weight", "base_model.conv2_3x3_reduce_bn.running_var", "base_model.conv2_3x3_reduce_bn.bias", "base_model.conv2_3x3_reduce_bn.weight", "base_model.conv2_3x3_reduce_bn.running_mean", "base_model.conv2_3x3.bias", "base_model.conv2_3x3.weight", "base_model.conv2_3x3_bn.running_var", "base_model.conv2_3x3_bn.bias", "base_model.conv2_3x3_bn.weight", "base_model.conv2_3x3_bn.running_mean", "base_model.inception_3a_1x1.bias", "base_model.inception_3a_1x1.weight", "base_model.inception_3a_1x1_bn.running_var", "base_model.inception_3a_1x1_bn.bias", "base_model.inception_3a_1x1_bn.weight", "base_model.inception_3a_1x1_bn.running_mean", "base_model.inception_3a_3x3_reduce.bias", "base_model.inception_3a_3x3_reduce.weight", "base_model.inception_3a_3x3_reduce_bn.running_var", "base_model.inception_3a_3x3_reduce_bn.bias", "base_model.inception_3a_3x3_reduce_bn.weight", "base_model.inception_3a_3x3_reduce_bn.running_mean", "base_model.inception_3a_3x3.bias", "base_model.inception_3a_3x3.weight", "base_model.inception_3a_3x3_bn.running_var", "base_model.inception_3a_3x3_bn.bias", "base_model.inception_3a_3x3_bn.weight", "base_model.inception_3a_3x3_bn.running_mean", "base_model.inception_3a_double_3x3_reduce.bias", "base_model.inception_3a_double_3x3_reduce.weight", "base_model.inception_3a_double_3x3_reduce_bn.running_var", "base_model.inception_3a_double_3x3_reduce_bn.bias", "base_model.inception_3a_double_3x3_reduce_bn.weight", "base_model.inception_3a_double_3x3_reduce_bn.running_mean", "base_model.inception_3a_double_3x3_1.bias", "base_model.inception_3a_double_3x3_1.weight", "base_model.inception_3a_double_3x3_1_bn.running_var", "base_model.inception_3a_double_3x3_1_bn.bias", "base_model.inception_3a_double_3x3_1_bn.weight", "base_model.inception_3a_double_3x3_1_bn.running_mean", "base_model.inception_3a_double_3x3_2.bias", "base_model.inception_3a_double_3x3_2.weight", "base_model.inception_3a_double_3x3_2_bn.running_var", "base_model.inception_3a_double_3x3_2_bn.bias", "base_model.inception_3a_double_3x3_2_bn.weight", "base_model.inception_3a_double_3x3_2_bn.running_mean", "base_model.inception_3a_pool_proj.bias", "base_model.inception_3a_pool_proj.weight", "base_model.inception_3a_pool_proj_bn.running_var", "base_model.inception_3a_pool_proj_bn.bias", "base_model.inception_3a_pool_proj_bn.weight", "base_model.inception_3a_pool_proj_bn.running_mean", "base_model.inception_3b_1x1.bias", "base_model.inception_3b_1x1.weight", "base_model.inception_3b_1x1_bn.running_var", "base_model.inception_3b_1x1_bn.bias", "base_model.inception_3b_1x1_bn.weight", "base_model.inception_3b_1x1_bn.running_mean", "base_model.inception_3b_3x3_reduce.bias", "base_model.inception_3b_3x3_reduce.weight", "base_model.inception_3b_3x3_reduce_bn.running_var", "base_model.inception_3b_3x3_reduce_bn.bias", "base_model.inception_3b_3x3_reduce_bn.weight", "base_model.inception_3b_3x3_reduce_bn.running_mean", "base_model.inception_3b_3x3.bias", "base_model.inception_3b_3x3.weight", "base_model.inception_3b_3x3_bn.running_var", "base_model.inception_3b_3x3_bn.bias", "base_model.inception_3b_3x3_bn.weight", "base_model.inception_3b_3x3_bn.running_mean", "base_model.inception_3b_double_3x3_reduce.bias", "base_model.inception_3b_double_3x3_reduce.weight", "base_model.inception_3b_double_3x3_reduce_bn.running_var", "base_model.inception_3b_double_3x3_reduce_bn.bias", "base_model.inception_3b_double_3x3_reduce_bn.weight", "base_model.inception_3b_double_3x3_redu

**Comment by fubel** [comment]
I'm not familiar with the `test_video.py` from TRN-PyTorch. We use BNInception from the `pretrainedmodels` package, whereas TRN-PyTorch seems to use it from `model_zoo`. There might be a slight difference. 

You could have a look at the validation loop and resume section in our `main.py` and see how we load models for continuing training, then adapt the `test_video.py` from TRN-PyTorch accordingly.

**Comment by ranjitswami** [comment]
Hello @fubel,

I have resolved issue. I have made required changes in test_video. py file. 
I conducted test with different sample and got expected results.

Shall I add same in this repo to help others users?

Really thanks for your reply.

**Comment by fubel** [comment]
Hi @ranjitswami, adding it to the repo would be very nice. Thank you!
